---
- name: Update apt package index
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages for Docker
  become: yes
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: Update apt package index after adding Docker repo
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker CE
  become: yes
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Ensure Docker service is running
  become: yes
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add vagrant user to docker group
  become: yes
  ansible.builtin.user:
    name: vagrant
    groups:
      - docker
    append: yes