---
- name: Upgrade OS
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  tags:
    - first_upgrade

- name: Install the build tools and mandatory requirements
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - cmake
    - make
    - g++
    - pkg-config
    - libfftw3-dev
    - libmbedtls-dev
    - libsctp-dev
    - libyaml-cpp-dev
    - libgtest-dev
    - libzmq3-dev
    - libboost-program-options-dev
    - libconfig++-dev
    - iperf