---
- name: Create oran directory
  become: true
  ansible.builtin.file:
    path: /oran
    owner: vagrant
    group: vagrant
    mode: '0755'
    state: directory

- name: Ensure repositories are cloned or updated from GitHub
  ansible.builtin.git:
    repo: "{{ item.value.address }}"
    dest: "/oran/{{ item.key }}"
    version: "{{ item.value.commit }}"
    update: yes
  loop: "{{ repos | dict2items }}"
  when: repos is defined

- name: Create directory for ue config
  ansible.builtin.file:
    path: /home/vagrant/.config/srsran/
    owner: vagrant
    group: vagrant
    mode: '0700'
    state: directory
  tags:
    - add_ue

- name: Copy ue config
  ansible.builtin.copy:
    src: ue.conf
    dest: /home/vagrant/.config/srsue/
  tags:
    - add_ue

- name: Copy gnb config
  become: yes
  ansible.builtin.copy:
    src: gnb_zmq.yaml
    dest: /oran/